import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

// const outFit = Outfit({ subsets: ["latin"], weight: "600" });

const OutfitSans = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hotch-Potch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${OutfitSans.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
